trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'implicixpublic'
    repository: 'implicix-dotnet7'
    command: build
    dockerfile: ./dotnet7/Dockerfile
    tags: |
      latest

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'implicixpublic'
    repository: 'implicix-dotnet7'
    command: push
    tags: | 
      latest
