trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'implicixpublic'
    repository: 'implicix-dotnet8'
    command: build
    dockerfile: ./dotnet8/Dockerfile
    tags: |
      latest

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'implicixpublic'
    repository: 'implicix-dotnet8'
    command: push
    tags: | 
      latest
